
const historyData = [
  {
    id: "*********",
    transactionType: "Payment",
    date: "**.**.20**",
    amount: "***STX",
    ngn: "*****",
    receiverAddress: "*********...",
    paymentType: "STX Transfer",
    status: "Completed",
  },]
// const historyData = [
//     {
//       id: "AXNB12345",
//       transactionType: "Payment",
//       date: "12.04.2022",
//       amount: "122STX",
//       ngn: "100,000",
//       receiverAddress: "Q0GP2DPPE4H9N0...",
//       paymentType: "STX Transfer",
//       status: "Completed",
//     },
//     {
//       id: "AXNB12345",
//       transactionType: "Payment",
//       date: "12.04.2022",
//       amount: "122STX",
//       ngn: "100,000",
//       receiverAddress: "Q0GP2DPPE4H9N0...",
//       paymentType: "STX Transfer",
//       status: "Completed",
//     },
//     {
//       id: "AXNB12345",
//       transactionType: "Payment",
//       date: "12.04.2022",
//       amount: "122STX",
//       ngn: "100,000",
//       receiverAddress: "Q0GP2DPPE4H9N0...",
//       paymentType: "STX Transfer",
//       status: "Cancelled",
//     },
//     {
//       id: "AXNB12345",
//       transactionType: "Payment",
//       date: "12.04.2022",
//       amount: "122STX",
//       ngn: "100,000",
//       receiverAddress: "Q0GP2DPPE4H9N0...",
//       paymentType: "STX Transfer",
//       status: "Pending",
//     },
//     {
//       id: "AXNB12345",
//       transactionType: "Payment",
//       date: "12.04.2022",
//       amount: "122STX",
//       ngn: "100,000",
//       receiverAddress: "Q0GP2DPPE4H9N0...",
//       paymentType: "STX Transfer",
//       status: "Cancelled",
//     },
//     {
//       id: "AXNB12345",
//       transactionType: "Payment",
//       date: "12.04.2022",
//       amount: "122STX",
//       ngn: "100,000",
//       receiverAddress: "Q0GP2DPPE4H9N0...",
//       paymentType: "STX Transfer",
//       status: "Completed",
//     },
//     {
//       id: "AXNB12345",
//       transactionType: "Payment",
//       date: "12.04.2022",
//       amount: "122STX",
//       ngn: "100,000",
//       receiverAddress: "Q0GP2DPPE4H9N0...",
//       paymentType: "STX Transfer",
//       status: "Pending",
//     },
//     {
//       id: "AXNB12345",
//       transactionType: "Payment",
//       date: "12.04.2022",
//       amount: "122STX",
//       ngn: "100,000",
//       receiverAddress: "Q0GP2DPPE4H9N0...",
//       paymentType: "STX Transfer",
//       status: "Pending",
//     },
//     {
//       id: "AXNB12345",
//       transactionType: "Payment",
//       date: "12.04.2022",
//       amount: "122STX",
//       ngn: "100,000",
//       receiverAddress: "Q0GP2DPPE4H9N0...",
//       paymentType: "STX Transfer",
//       status: "Pending",
//     },
//     {
//       id: "AXNB12345",
//       transactionType: "Payment",
//       date: "12.04.2022",
//       amount: "122STX",
//       ngn: "100,000",
//       receiverAddress: "Q0GP2DPPE4H9N0...",
//       paymentType: "STX Transfer",
//       status: "Pending",
//     },
//     {
//       id: "AXNB12345",
//       transactionType: "Payment",
//       date: "12.04.2022",
//       amount: "122STX",
//       ngn: "100,000",
//       receiverAddress: "Q0GP2DPPE4H9N0...",
//       paymentType: "STX Transfer",
//       status: "Pending",
//     },
//     {
//       id: "AXNB12345",
//       transactionType: "Payment",
//       date: "12.04.2022",
//       amount: "122STX",
//       ngn: "100,000",
//       receiverAddress: "Q0GP2DPPE4H9N0...",
//       paymentType: "STX Transfer",
//       status: "Pending",
//     },
//     {
//       id: "AXNB12345",
//       transactionType: "Payment",
//       date: "12.04.2022",
//       amount: "122STX",
//       ngn: "100,000",
//       receiverAddress: "Q0GP2DPPE4H9N0...",
//       paymentType: "STX Transfer",
//       status: "Pending",
//     },
//     {
//       id: "AXNB12345",
//       transactionType: "Payment",
//       date: "12.04.2022",
//       amount: "122STX",
//       ngn: "100,000",
//       receiverAddress: "Q0GP2DPPE4H9N0...",
//       paymentType: "STX Transfer",
//       status: "Pending",
//     },
//     {
//       id: "AXNB12345",
//       transactionType: "Payment",
//       date: "12.04.2022",
//       amount: "122STX",
//       ngn: "100,000",
//       receiverAddress: "Q0GP2DPPE4H9N0...",
//       paymentType: "STX Transfer",
//       status: "Pending",
//     },
//     {
//       id: "AXNB12345",
//       transactionType: "Payment",
//       date: "12.04.2022",
//       amount: "122STX",
//       ngn: "100,000",
//       receiverAddress: "Q0GP2DPPE4H9N0...",
//       paymentType: "STX Transfer",
//       status: "Pending",
//     },
//     {
//       id: "AXNB12345",
//       transactionType: "Payment",
//       date: "12.04.2022",
//       amount: "122STX",
//       ngn: "100,000",
//       receiverAddress: "Q0GP2DPPE4H9N0...",
//       paymentType: "STX Transfer",
//       status: "Pending",
//     },
//     {
//       id: "AXNB12345",
//       transactionType: "Payment",
//       date: "12.04.2022",
//       amount: "122STX",
//       ngn: "100,000",
//       receiverAddress: "Q0GP2DPPE4H9N0...",
//       paymentType: "STX Transfer",
//       status: "Pending",
//     },
//     {
//       id: "AXNB12345",
//       transactionType: "Payment",
//       date: "12.04.2022",
//       amount: "122STX",
//       ngn: "100,000",
//       receiverAddress: "Q0GP2DPPE4H9N0...",
//       paymentType: "STX Transfer",
//       status: "Pending",
//     },
//     {
//       id: "AXNB12345",
//       transactionType: "Payment",
//       date: "12.04.2022",
//       amount: "122STX",
//       ngn: "100,000",
//       receiverAddress: "Q0GP2DPPE4H9N0...",
//       paymentType: "STX Transfer",
//       status: "Pending",
//     },
//     {
//       id: "AXNB12345",
//       transactionType: "Payment",
//       date: "12.04.2022",
//       amount: "122STX",
//       ngn: "100,000",
//       receiverAddress: "Q0GP2DPPE4H9N0...",
//       paymentType: "STX Transfer",
//       status: "Pending",
//     },
//     {
//       id: "AXNB12345",
//       transactionType: "Payment",
//       date: "12.04.2022",
//       amount: "122STX",
//       ngn: "100,000",
//       receiverAddress: "Q0GP2DPPE4H9N0...",
//       paymentType: "STX Transfer",
//       status: "Pending",
//     },
//   ];

  export default historyData;